In [88]:
import numpy as np

In [89]:
# integer of size 8 bytes
myarr = np.array([[1,2, 3,4]], np.int64)

In [90]:
myarr.shape

(1, 4)

In [91]:
myarr[0].shape

(4,)

In [92]:
myarr.dtype

dtype('int64')

In [93]:
myarr[0, 1]

2

In [94]:
myarr[0, 1] = 34

In [95]:
myarr

array([[ 1, 34,  3,  4]])

In [96]:
# Array creation: Conversion from other Python structures (i.e. lists and tuples)

In [97]:
listarray = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [98]:
listarray.dtype

dtype('int64')

In [99]:
listarray.shape

(3, 3)

In [100]:
listarray.size

9

In [101]:
# Not recommended for calculation
np.array({34,23,36})

array({34, 36, 23}, dtype=object)

In [102]:
# array creation: Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [103]:
zeros = np.zeros((2,5))

In [104]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [105]:
zeros.shape

(2, 5)

In [106]:
rng = np.arange(15)

In [107]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [108]:
lspace = np.linspace(1, 50, 12)

In [109]:
lspace

array([ 1.        ,  5.45454545,  9.90909091, 14.36363636, 18.81818182,
       23.27272727, 27.72727273, 32.18181818, 36.63636364, 41.09090909,
       45.54545455, 50.        ])

In [110]:
lspace = np.linspace(1, 4, 4)
lspace
lspace.dtype

dtype('float64')

In [111]:
# Filled with random values. size 4,6
emp = np.empty((4,6))
emp

array([[2.27958174e-316, 0.00000000e+000, 9.82157975e+252,
        8.89489936e+252, 6.01346954e-154, 6.01347002e-154],
       [6.01347002e-154, 6.01347002e-154, 9.08366793e+223,
        1.14177168e+243, 2.45126797e+198, 1.06083187e-153],
       [2.35625393e+251, 6.01334511e-154, 6.01347002e-154,
        6.01347002e-154, 6.01347002e-154, 1.88556770e+122],
       [4.96820036e+180, 6.80600993e+212, 1.10317376e+217,
        1.19490107e+190, 2.06642651e+161, 5.44760669e-109]])

In [112]:
# empty_like: Return a new array with the same shape and type as a given array.
emp_like = np.empty_like(lspace)
emp_like

array([1., 2., 3., 4.])

In [113]:
# identity matrix
# creates a square matrix with ones on the diagonal and zeros elsewhere
# shape nxn
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [114]:
# reshape
arr = np.arange(99)

arr = arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [115]:
# again making it 1D
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [116]:
# numpy axis
# axis 0 is vertical axis 1 is horizontal
# For 2D array, axis 0 is vertical (along the rows) and axis 1 is horizontal (along the columns)
# For 1D array, axis 0 is horizontal

In [117]:
x = [[1,2,3], 
     [4,5,6], 
     [7,1,0]]
arr = np.array(x)
arr.sum(axis=0)

array([12,  8,  9])

In [118]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [119]:
# For transpose
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [120]:
# For flat. It returns a 1D iterator over the array
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [121]:
# ndim - number of dimensions
arr.ndim

2

In [122]:
arr.size

9

In [123]:
arr.nbytes

72

In [124]:
one = np.array([1, 3, 4, 634, 23])

In [125]:
# argmax - returns the index of the maximum value in the array
one.argmax()

3

In [126]:
# argmin - returns the index of the minimum value in the array
one.argmin()

0

In [127]:
# argsort - returns the indices that would sort the array
one.argsort()

array([0, 1, 2, 4, 3])

In [128]:
# for 2d array
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [129]:
arr.argmin()

8

In [130]:
arr.argmax()

6

In [131]:
arr.argmax(axis=0)

array([2, 1, 1])

In [132]:
arr.argmax(axis=1)

array([2, 2, 0])

In [133]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [134]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [135]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [136]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [137]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [138]:
arr2 = np.array([[1,2,1], 
                 [4,0,6], 
                 [8,1,0]])

In [139]:
arr + arr2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [140]:
[324, 23, 23] + [23, 23, 23]

[324, 23, 23, 23, 23, 23]

In [141]:
# element wise multiplication
arr * arr2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [143]:
# Element wise square root
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [144]:
arr.sum()

29

In [145]:
arr.max()

7

In [146]:
arr.min()

0

In [147]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [148]:
# Position of max element. Returns tuple of indices
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [149]:
# returns the number of non-zero elements in the array
np.count_nonzero(arr)

8

In [150]:
# returns tuples of indices of non-zero elements
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [151]:
# to list
arr.tolist()

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]